stages:
    - verify
    - test
    - deploy
    - release

Verify:
    stage: verify
    script:
        - mvn verify
    tags:
        - verify

Test:
    stage: test
    script:
        - echo TEST
    tags:
        - test

Deploy:
    stage: deploy
    script:
        - mvn --settings settings.xml deploy
    only:
        - develop
    tags:
        - deploy

Release:
    stage: release
    script:
        - mvn release:prepare release:perform 
    only:
        - master
    tags:
        - release
