stages:
    - verify
    - delivery
    - deployment
    
Verify1:
    stage: verify
    script:
        - mvn verify
    tags:
        - verify

Delivery1:
    stage: delivery
    script:
        - echo DELIVERED
    except:
        - master
    tags:
        - Delivery

Deployment1:
    stage: deployment
    script:
       - echo DEPLOYED
    only:
        - master
    tags:
        - deployment
