stages:
    - test
    - verify
    - deploy
    - release

Test:
    stage: test
    script:
        - echo TEST
    tags:
        - test

Verify:
    stage: verify
    script:
        - mvn verify
    only:
        - develop
    tags:
        - verify

Deploy:
    stage: deploy
    script:
        - mvn clean deploy
    only:
        - develop
    tags:
        - deploy

Release:
    stage: release
    script:
       - mvn clean deploy
    only:
        - master
    tags:
        - release